version: '3.7'

services:
  lna:
    build: .
    volumes:
      - ./src:/usr/app/src
      - ./skywater-pdk/tt.spice:/edatools/skywater-pdk/libraries/sky130_fd_pr/latest/models/corners/tt.spice
    deploy:
      resources:
        limits:
          memory: 1024M
        reservations:
          memory: 128M
    restart: always
  
  nginx:
    build: nginx
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 3333:80
    depends_on:
      - lna

